config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    collection do
      post :confirm
		end
  end
  resources :niarest_stations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nearest_station.rb
class NearestStation < ApplicationRecord
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  validates :name, presence: true
  has_many :nearest_stations, dependent: :destroy
  accepts_nested_attributes_for :nearest_stations, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def new
    if params[:back]
		  @property = Property.new(property_params)
    else
      @property = Property.new
      2.times { @property.nearest_stations.build }
    end
  end

  def show
  end

  def edit
    @property.nearest_stations.build
  end

  def create
    @property = Property.new(property_params)
      if params[:back]
        render :new
      else
        if @property.save
          redirect_to properties_path, notice:"Property was successfully created！"
        else
          render :new
        end
      end
  end

  def update
	    if @property.update(property_params)
	      redirect_to properties_path, notice: "Property was successfully updated！"
	    else
	      render :edit
      end
  end

  def destroy
    @property.destroy
      redirect_to properties_path, notice:"Property was successfully destroyed！"
  end

  def confirm
		@property = Property.new(property_params)
    render :new if @property.invalid?
	end


  private
  def property_params
    params.require(:property).permit(:name, :rent, :address, :year, :memo, nearest_stations_attributes:[:id, :station, :route, :time])
  end

  def set_property
    @property = Property.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_properties_path
    elsif action_name == 'edit'
      property_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: @property, local: true ,url: choose_new_or_edit ) do |form| %>
<% if @property.errors.any? %>
　<div id="error_explanation">
　　<h2><%= @property.errors.count %>There are some errors.</h2>
　　<ul>
　　<% @property.errors.full_messages.each do |msg| %>
　　　<li><%= msg %></li>
　　<% end %>
　　</ul>
　</div>
<% end %>

  <div class="property">
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <%= form.label :rent %><br>
    <%= form.text_field :rent %><br>
    <%= form.label :address %><br>
    <%= form.text_field :address %><br>
    <%= form.label :year %><br>
    <%= form.text_field :year %><br>
    <%= form.label :remarks %><br>
    <%= form.text_area :memo %><br>
  </div>
<hr>
  <div class="station">
    <% n = 0 %>
    <%= form.fields_for :nearest_stations do |near| %>
      <h2>Nearest Station<%= n += 1 %></h2>
      <%= near.label :Route %><br>
      <%= near.text_field :route %><br>
      <%= near.label :Station %><br>
      <%= near.text_field :station %><br>
      <%= near.label :Time %><br>
      <%= near.text_field :time %><br>
    <% end %>
  </div>
　<%= form.submit %>
<% end %>
<%= link_to "back", properties_path %>

app/views/properties/confirm.html.erb
<h3>Send with the following contents.</h3>
<%= form_with(model: @property, url: properties_path, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :rent %>
  <%= form.hidden_field :address %>
  <%= form.hidden_field :year %>
  <%= form.hidden_field :memo %>
  <p>name:<%= @property.name %></p>
  <p>rent:<%= @property.rent %></p>
  <p>address:<%= @property.address %></p>
  <p>year:<%= @property.year %></p>
  <p>remarks:<%= @property.memo %></p>
  <%= form.submit  "confirm" %>
  <%= form.submit "back", name: 'back' %>
<% end %>

app/views/properties/edit.html.erb
<h2>Edit property</h2>
<%= render 'form' %>

<%= link_to 'back', property_path %>

app/views/properties/index.html.erb
<h1>Property list</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>Property Name</th>
    <th>Rent</th>
    <th>Address</th>
    <th>Year</th>
    <th>Remarks</th>
　</tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.name %></td>
    <td><%= property.rent.to_s(:delimited) %></td>
    <td><%= property.address %></td>
    <td><%= property.year %></td>
    <td><%= property.memo %></td>
    <td><%= link_to "show", property_path(property.id) %></td>
    <td><%= link_to "edit", edit_property_path(property.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to "delete", property_path(property.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'Create New', new_property_path %>

app/views/properties/new.html.erb
<h2>Register property </h2>
<%= render 'form' %>

app/views/properties/show.html.erb
<h1>Property details </h1>
<p>Name: <%= @property.name %></p>
<p>Rent: <%= @property.rent %></p>
<p>Adress: <%= @property.address %></p>
<p>Year: <%= @property.year %></p>
<p>Remarks: <%= @property.memo %></p>
<hr> 
<div class="station">
  <% n = 0 %>
  <% @property.nearest_stations.each do |nearest_station| %>
    <h2>Nearest Station<%= n += 1 %></h2>
      <p>
        <strong>Route:</strong><%= nearest_station.route %>
      </p>
      <p>
        <strong>Station:</strong><%= nearest_station.station %>
      </p>
      <p>
        <strong>Time:</strong><%= nearest_station.time %>
      </p>
  <% end %>
</div>

<%= link_to 'edit', edit_property_path %> |
<%= link_to 'back', properties_path %>